motd=A Craftbox Server
max-players=20
difficulty=normal
gamemode=survival
view-distance=10
simulation-distance=10
online-mode=true
pvp=true
spawn-animals=true
spawn-monsters=true
spawn-protection=0
level-type=minecraft\:normal
